import { notFound } from 'next/navigation';
export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { db } from '@/lib/db';
import { getCurrentUser } from '@/lib/auth';
import { AppShell, Icon } from '@/components/app-shell';

/**
 * /submissions/[id]/report — links to the generated PDF for a submission.
 *
 * (The actual PDF is generated by GET /api/submissions/[id]/pdf.)
 */
export default async function SubmissionReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: rawId } = await params;
  // URL-decode in case the colons in ISO timestamps are percent-encoded
  const submissionIdStr = decodeURIComponent(rawId);
  const user = await getCurrentUser();
  if (!user) return notFound();

  let submissionDate: Date;
  try {
    submissionDate = new Date(submissionIdStr);
    if (isNaN(submissionDate.getTime())) return notFound();
  } catch {
    return notFound();
  }

  // Find the submission (timestamp-based ID)
  const all = await db.submission.findMany({ take: 500 });
  const submission = all.find((s) => {
    if (!(s.id instanceof Date)) return false;
    return s.id.getTime() === submissionDate.getTime();
  });
  if (!submission) return notFound();

  const form = await db.form.findFirst({ where: { id: submission.formId, ownerId: user.id } });
  if (!form) return notFound();

  return (
    <AppShell activePath="/submissions" brandSubtitle="PDF report">
      <div className="min-h-screen bg-rf-surface-base text-rf-on-surface">
        <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-12">
          <div className="mb-6 flex flex-wrap items-center gap-2 text-[12px] text-rf-on-surface-variant">
            <Link href="/submissions" className="transition-colors hover:text-rf-primary">
              Submissions
            </Link>
            <Icon name="chevron_right" className="text-[14px]" />
            <span className="font-semibold text-rf-on-surface">{form.name}</span>
          </div>

          <header className="mb-8">
            <h1 className="text-[28px] font-bold tracking-tight sm:text-[32px]">
              Submission report
            </h1>
            <p className="mt-2 text-[15px] text-rf-on-surface-variant">
              A branded PDF report has been generated for this submission, including AI-written analyst notes.
            </p>
          </header>

          <div className="rounded-2xl border border-rf-border-white-faint bg-rf-surface-container/50 p-6">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <div className="text-[11px] font-semibold uppercase tracking-wider text-rf-on-surface-variant">
                  Form
                </div>
                <div className="text-[18px] font-bold text-rf-on-surface">{form.name}</div>
                <div className="mt-1 text-[12px] text-rf-on-surface-variant">
                  Submitted {submissionDate.toLocaleString()}
                </div>
              </div>
              <a
                href={`/api/submissions/${submissionIdStr}/pdf`}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary flex items-center gap-2 rounded-lg px-5 py-2.5 text-[13px] font-bold"
              >
                <Icon name="picture_as_pdf" className="text-[18px]" />
                Download PDF
              </a>
            </div>
          </div>

          <details className="mt-6 rounded-xl border border-rf-border-white-faint bg-rf-surface-container/30 p-4">
            <summary className="cursor-pointer list-none text-[12px] font-semibold text-rf-on-surface">
              <div className="flex items-center gap-2">
                <Icon name="hub" className="text-[14px] text-rf-primary" />
                What&apos;s in the PDF
              </div>
            </summary>
            <ul className="mt-3 list-disc space-y-1 pl-5 text-[11px] leading-relaxed text-rf-on-surface-variant">
              <li>Reform branding header + form name + description</li>
              <li>Submission metadata (timestamp, source, status, IDs)</li>
              <li>Field-by-field responses (label + value)</li>
              <li>AI-generated &quot;Analyst notes&quot; — the LLM writes 3-5 sentences summarising the submission, flagging anomalies or follow-ups. Generated via z-ai-web-dev-sdk and audit-logged in Xano.</li>
              <li>Footer with page numbers + generation timestamp</li>
            </ul>
          </details>
        </div>
      </div>
    </AppShell>
  );
}
