import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Img,
  Video,
  interpolate,
  staticFile,
  useCurrentFrame,
} from 'remotion';
import SCENES_MEASURED from './scenes-3min.json';

const W = 1920;
const H = 1040;
const FPS = 30;
const DURATION = 180;

const C = {
  bg: '#070909',
  bg2: '#0b1110',
  line: '#1e3229',
  text: '#f5f7f2',
  muted: '#a5b2aa',
  muted2: '#6b8178',
  amber: '#f5a828',
  amberLight: '#ffd06a',
  mint: '#6ee0a4',
};

const asset = (name: string) => staticFile(`reform-assets/${name}`);

const clamp = { extrapolateLeft: 'clamp' as const, extrapolateRight: 'clamp' as const };
const easeIO = (p: number) => {
  const c = Math.max(0, Math.min(1, p));
  return c * c * (3 - 2 * c);
};

// Scene timeline (seconds) — identical to reform-hyperframes/demo.html, aligned to the narration cue sheet.
// start/end/creditAt are overwritten by the measured times from scenes-3min.json (generated by
// build-scenes-3min.js after a re-narration), so picture and voice stay locked.
type Scene =
  | { type: 'title'; id: string; start: number; end: number; eyebrow: string; title: string; body: string; meta: string }
  | { type: 'media'; id: string; start: number; end: number; shots?: Shot[]; video?: string; videoStart?: number; move?: Move; fadeOut?: number }
  | { type: 'grid'; id: string; start: number; end: number; eyebrow: string; title: string; sub: string; tiles: { img: string; name: string }[] }
  | { type: 'end'; id: string; start: number; end: number; creditAt: number };

interface Move { z0: number; z1: number; x0: number; y0: number; x1: number; y1: number }
interface Shot { img: string; dur: number; move: Move }

const SCENES: Scene[] = [
  { id: 'title', type: 'title', start: 0.000, end: 12.170, eyebrow: 'REFORM',
    title: 'Forms are not documents.\nThey are conversations.',
    body: 'The first conversation between a team and the people it serves — captured, structured, and put to work.',
    meta: 'A tour of the operating system for better forms.' },

  { id: 'montage', type: 'media', start: 12.170, end: 22.740, shots: [
    { img: 'ai-gen.png', dur: 2.64, move: { z0: 1.10, z1: 1.0, x0: -70, y0: -30, x1: 0, y1: 0 } },
    { img: 'builder.png', dur: 2.64, move: { z0: 1.0, z1: 1.10, x0: 0, y0: 0, x1: 60, y1: -20 } },
    { img: 'chat.png', dur: 2.64, move: { z0: 1.12, z1: 1.02, x0: 50, y0: 24, x1: 0, y1: 0 } },
    { img: 'submissions.png', dur: 2.65, move: { z0: 1.02, z1: 1.10, x0: 0, y0: 0, x1: -56, y1: 26 } },
  ] },

  { id: 'dashboard', type: 'media', start: 22.740, end: 40.540, video: 'first.mp4', videoStart: 3.2, move: { z0: 1.0, z1: 1.05, x0: 0, y0: 0, x1: 0, y1: 0 } },

  { id: 'gen-prompt', type: 'media', start: 40.540, end: 55.190, shots: [
    { img: 'ai-gen.png', dur: 14.65, move: { z0: 1.02, z1: 1.13, x0: 0, y0: 0, x1: -72, y1: -34 } },
  ] },

  { id: 'generator', type: 'media', start: 55.190, end: 63.970, shots: [
    { img: 'ai-gen.png', dur: 8.78, move: { z0: 1.16, z1: 1.06, x0: 60, y0: -40, x1: 0, y1: 0 } },
  ] },

  { id: 'builder', type: 'media', start: 63.970, end: 85.540, shots: [
    { img: 'builder.png', dur: 10.785, move: { z0: 1.0, z1: 1.09, x0: 0, y0: 0, x1: -58, y1: -24 } },
    { img: 'builder.png', dur: 10.785, move: { z0: 1.14, z1: 1.04, x0: 80, y0: 44, x1: 0, y1: 14 } },
  ] },

  { id: 'chat', type: 'media', start: 85.540, end: 99.600, shots: [
    { img: 'chat.png', dur: 14.06, move: { z0: 1.05, z1: 1.0, x0: -30, y0: -26, x1: 0, y1: 0 } },
  ] },

  { id: 'voice-translate', type: 'media', start: 99.600, end: 108.940, shots: [
    { img: 'voice.png', dur: 4.67, move: { z0: 1.12, z1: 1.03, x0: 54, y0: -30, x1: 0, y1: 0 } },
    { img: 'translate.png', dur: 4.67, move: { z0: 1.03, z1: 1.12, x0: 0, y0: 0, x1: -60, y1: 22 } },
  ] },

  { id: 'submissions', type: 'media', start: 108.940, end: 123.870, shots: [
    { img: 'submissions.png', dur: 14.93, move: { z0: 1.02, z1: 1.14, x0: 0, y0: 0, x1: 66, y1: -38 } },
  ] },

  { id: 'metrics', type: 'media', start: 123.870, end: 129.810, shots: [
    { img: 'dashboard.png', dur: 5.94, move: { z0: 1.08, z1: 1.18, x0: 0, y0: -40, x1: -46, y1: -64 } },
  ] },

  { id: 'analytics', type: 'media', start: 129.810, end: 136.320, shots: [
    { img: 'analytics.png', dur: 6.51, move: { z0: 1.16, z1: 1.05, x0: -70, y0: 36, x1: 0, y1: 0 } },
  ] },

  { id: 'mosaic', type: 'grid', start: 136.320, end: 146.210,
    eyebrow: 'ONE PLATFORM', title: 'Every AI feature. One intelligent system.',
    sub: 'Command center · generator · visual logic · conversational · voice · translation · routing · analytics · API',
    tiles: [
      { img: 'ai-gen.png', name: 'AI generator' }, { img: 'builder.png', name: 'Visual builder' },
      { img: 'chat.png', name: 'Conversational' }, { img: 'voice.png', name: 'Voice mode' },
      { img: 'translate.png', name: 'Translation' }, { img: 'routing.png', name: 'Smart routing' },
      { img: 'submissions.png', name: 'Submissions' }, { img: 'analytics.png', name: 'AI analytics' },
      { img: 'api-keys.png', name: 'REST API' }, { img: 'dashboard.png', name: 'Command center' },
    ] },

  { id: 'invitation', type: 'media', start: 146.210, end: 160.258, fadeOut: 0.9, shots: [
    { img: 'chat.png', dur: 4.7, move: { z0: 1.06, z1: 1.13, x0: -30, y0: -24, x1: -90, y1: -40 } },
    { img: 'translate.png', dur: 4.7, move: { z0: 1.0, z1: 1.09, x0: 0, y0: 0, x1: 56, y1: -26 } },
    { img: 'voice.png', dur: 4.648, move: { z0: 1.1, z1: 1.03, x0: 60, y0: 32, x1: 0, y1: 0 } },
  ] },

  { id: 'end', type: 'end', start: 160.258, end: 180.000, creditAt: 171.0 },
];

// Measured scene boundaries from the voice track override the fallback times above
// (scenes-3min.json is regenerated by build-scenes-3min.js after a re-narration).
const MEASURED = (SCENES_MEASURED as { scenes?: { id: string; start: number; end: number; creditAt?: number }[] }).scenes || [];
if (MEASURED.length) {
  for (const s of SCENES) {
    const t = MEASURED.find((x) => x.id === s.id);
    if (t) {
      s.start = t.start;
      s.end = t.end;
      if (typeof t.creditAt === 'number') (s as { creditAt?: number }).creditAt = t.creditAt;
    }
  }
}

const railShown = (s: Scene) => s.type !== 'media';

const currentScene = (sec: number): Scene => {
  for (const s of SCENES) {
    if (sec >= s.start && sec < s.end) return s;
  }
  return SCENES[SCENES.length - 1];
};

// ────────────────────────────────────────────────────────────────
// Shared chrome
// ────────────────────────────────────────────────────────────────
const Backdrop: React.FC = () => (
  <AbsoluteFill style={{
    background: `radial-gradient(ellipse 900px 600px at 62% 32%, #0e2a1c14, transparent 60%),
    radial-gradient(ellipse 700px 500px at 25% 75%, #0a1a1410, transparent 55%),
    linear-gradient(165deg, ${C.bg}, ${C.bg2} 45%, #080c0a 70%, ${C.bg})`,
  }}>
    <AbsoluteFill style={{
      opacity: 0.07,
      backgroundImage: 'linear-gradient(rgba(255,255,255,0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.045) 1px, transparent 1px)',
      backgroundSize: '80px 80px',
      maskImage: 'radial-gradient(ellipse 80% 70% at 50% 50%, #000 30%, transparent 80%)',
    }} />
  </AbsoluteFill>
);

const Vignette: React.FC = () => (
  <AbsoluteFill style={{ pointerEvents: 'none', background: 'radial-gradient(ellipse 80% 78% at 50% 50%, transparent 48%, rgba(0,0,0,0.5) 100%)' }} />
);

const Rail: React.FC<{ scene: Scene; index: number }> = ({ scene, index }) => {
  const frame = useCurrentFrame();
  const shown = railShown(scene);
  const sec = frame / FPS;
  const span = H - 96 - 96 - 84;
  const frac = (SCENES.length - 1) <= 0 ? 0 : index / (SCENES.length - 1);
  return <>
    <div style={{
      position: 'absolute', left: 66, top: 96, bottom: 96, width: 2,
      background: C.line, zIndex: 60, opacity: shown ? 1 : 0,
    }} />
    <div style={{
      position: 'absolute', left: 63, top: 96 + frac * span, width: 8, height: 84, borderRadius: 8,
      background: `linear-gradient(180deg, ${C.amberLight}, ${C.amber})`,
      boxShadow: `0 0 22px ${C.amber}`, opacity: shown ? 1 : 0,
    }} />
    <div style={{
      position: 'absolute', left: 48, top: 64, color: C.muted2,
      font: '600 15px monospace', letterSpacing: '0.2em', zIndex: 60, opacity: shown ? 1 : 0,
      writingMode: 'vertical-rl' as const,
    }}>
      {String(index + 1).padStart(2, '0')} / {SCENES.length}
      <span style={{ opacity: 0 }}>{sec.toFixed(0)}</span>
    </div>
  </>;
};

// ────────────────────────────────────────────────────────────────
// Title scene
// ────────────────────────────────────────────────────────────────
const RealMark: React.FC<{ size?: number; glow?: number }> = ({ size = 60, glow = 1 }) => (
  <Img src={asset('reform-mark.png')} style={{
    width: size, height: size, objectFit: 'contain',
    filter: `drop-shadow(0 0 ${26 * glow}px ${C.amber}55) drop-shadow(0 0 ${60 * glow}px ${C.amber}22)`,
  }} />
);

const TitleScene: React.FC<{ scene: Extract<Scene, { type: 'title' }> }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const lf = Math.max(0, frame - scene.start * FPS);
  const y = 26 * (1 - easeIO(Math.max(0, Math.min(1, lf / 26))));
  const op = interpolate(frame, [scene.start * FPS, scene.start * FPS + 12], [0, 1], clamp);
  const line = easeIO(Math.max(0, Math.min(1, (lf - 6) / 34)));
  return (
    <AbsoluteFill style={{ opacity: op }}>
      <Backdrop />
      <div style={{
        position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
        textAlign: 'center', translate: `0px ${y}px`,
      }}>
        <div style={{ width: 1420 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 18, marginBottom: 44 }}>
            <RealMark size={60} />
            <span style={{ font: '600 34px Space Grotesk, sans-serif', letterSpacing: '-0.02em' }}>Reform</span>
          </div>
          <div style={{ color: C.amber, fontSize: 15, letterSpacing: '0.3em', fontWeight: 700, textTransform: 'uppercase' }}>
            {scene.eyebrow}
          </div>
          <h1 style={{
            margin: '24px auto 0', font: '700 82px/1.04 Space Grotesk, sans-serif',
            letterSpacing: '-0.055em', maxWidth: 1320, whiteSpace: 'pre-line',
          }}>
            {scene.title.split('\n').map((ln, i) => (
              <React.Fragment key={i}>
                {i > 0 && <><br /></>}
                {i === 1 ? <span style={{
                  background: `linear-gradient(135deg, ${C.amberLight}, ${C.amber}, #e89020)`,
                  WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text',
                }}>{ln}</span> : ln}
              </React.Fragment>
            ))}
          </h1>
          <div style={{
            width: `${line * 430}px`, height: 2, margin: '28px auto 0',
            background: `linear-gradient(90deg, transparent, ${C.amber}, transparent)`, boxShadow: `0 0 22px ${C.amber}88`,
          }} />
          <p style={{ margin: '28px auto 0', color: C.muted, fontSize: 28, lineHeight: 1.48, maxWidth: 1020 }}>
            {scene.body}
          </p>
          <div style={{
            display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 14, marginTop: 42,
            color: '#dbe4de', fontSize: 16,
          }}>
            <span style={{ width: 8, height: 8, borderRadius: '50%', background: C.amber, boxShadow: `0 0 18px ${C.amber}` }} />
            {scene.meta}
          </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ────────────────────────────────────────────────────────────────
// Media scene — real product screens, full-frame, textless
// ────────────────────────────────────────────────────────────────
const MediaShot: React.FC<{ startSec: number; endSec: number; shots: Shot[]; i: number }> = ({ startSec, endSec, shots, i }) => {
  const frame = useCurrentFrame();
  const local = Math.max(0, Math.min(endSec - startSec, frame / FPS - startSec));
  // distribute the measured scene duration evenly across the shots so the sequence
  // always covers the whole scene (never a dead gap after the last shot)
  const dur = (endSec - startSec) / shots.length;
  const a = i * dur;
  const b = a + dur;
  const pr = easeIO(Math.max(0, Math.min(1, (local - a) / dur)));
  const mv = shots[i].move;
  const z = mv.z0 + (mv.z1 - mv.z0) * pr;
  const x = mv.x0 + (mv.x1 - mv.x0) * pr;
  const y = mv.y0 + (mv.y1 - mv.y0) * pr;
  const fd = 0.42;
  let op = 1;
  if (local < a || local > b) op = 0;
  else if (i > 0 && local < a + fd) op = (local - a) / fd;
  else if (i < shots.length - 1 && local > b - fd) op = (b - local) / fd;
  return (
    <AbsoluteFill style={{ opacity: op }}>
      <AbsoluteFill style={{ translate: `${x}px ${y}px`, scale: String(z) }}>
        <Img src={asset(shots[i].img)} style={{ width: W, height: H, objectFit: 'cover' }} />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const MediaVideo: React.FC<{ s: Extract<Scene, { type: 'media' }> }> = ({ s }) => {
  const frame = useCurrentFrame();
  const local = Math.max(0, frame / FPS - s.start);
  const dur = s.end - s.start;
  const pr = easeIO(Math.max(0, Math.min(1, local / dur)));
  const mv = s.move ?? { z0: 1, z1: 1, x0: 0, y0: 0, x1: 0, y1: 0 };
  const z = mv.z0 + (mv.z1 - mv.z0) * pr;
  const x = mv.x0 + (mv.x1 - mv.x0) * pr;
  const y = mv.y0 + (mv.y1 - mv.y0) * pr;
  return (
    <AbsoluteFill>
      <AbsoluteFill style={{ translate: `${x}px ${y}px`, scale: String(z) }}>
        <Video
          src={asset(s.video!)}
          startFrom={Math.round((s.videoStart ?? 0) * FPS)}
          endAt={Math.round(((s.videoStart ?? 0) + dur) * FPS)}
          muted
          style={{ width: W, height: H, objectFit: 'cover' }}
        />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const MediaScene: React.FC<{ scene: Extract<Scene, { type: 'media' }> }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const sec = frame / FPS;
  const local = Math.max(0, Math.min(scene.end - scene.start, sec - scene.start));
  let hostOp = 1;
  if (scene.fadeOut && local > (scene.end - scene.start) - scene.fadeOut) {
    hostOp = 1 - easeIO((local - ((scene.end - scene.start) - scene.fadeOut)) / scene.fadeOut);
  }
  return (
    <AbsoluteFill style={{ opacity: hostOp }}>
      <AbsoluteFill style={{ background: '#050707' }} />
      {scene.video ? (
        <MediaVideo s={scene} />
      ) : (
        (scene.shots ?? []).map((_, i) => (
          <MediaShot key={i} startSec={scene.start} endSec={scene.end} shots={scene.shots as Shot[]} i={i} />
        ))
      )}
      {/* cinematic soft edges + grade */}
      <AbsoluteFill style={{
        pointerEvents: 'none', zIndex: 3,
        background:
          'linear-gradient(to bottom, rgba(5,7,7,0.4) 0%, transparent 11%),' +
          'linear-gradient(to top, rgba(5,7,7,0.48) 0%, transparent 12%),' +
          'linear-gradient(to right, rgba(5,7,7,0.32) 0%, transparent 7%),' +
          'linear-gradient(to left, rgba(5,7,7,0.32) 0%, transparent 7%)',
      }} />
      <AbsoluteFill style={{
        pointerEvents: 'none', zIndex: 4, mixBlendMode: 'soft-light',
        background: 'linear-gradient(135deg, rgba(245,168,40,0.05), rgba(30,90,60,0.06) 55%, rgba(20,40,90,0.06))',
      }} />
    </AbsoluteFill>
  );
};

// ────────────────────────────────────────────────────────────────
// Grid / mosaic scene
// ────────────────────────────────────────────────────────────────
const GridScene: React.FC<{ scene: Extract<Scene, { type: 'grid' }> }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const local = Math.max(0, Math.min(scene.end - scene.start, frame / FPS - scene.start));
  const p = local / (scene.end - scene.start);
  const tileW = (W - 92 * 2 - 24 * (scene.tiles.length / 2 - 1)) / (scene.tiles.length / 2);
  const tileImgH = tileW * (9 / 16);
  const nameH = 34;
  const gridH = (tileImgH + nameH) * 2 + 24;
  return (
    <AbsoluteFill style={{ zIndex: 10 }}>
      <Backdrop />
      <AbsoluteFill style={{
        left: '50%', top: '50%', width: 1700, height: 760,
        translate: '-50% -50%',
        background: 'radial-gradient(closest-side, rgba(245,168,40,0.06), transparent 72%)',
      }} />
      <div style={{ position: 'absolute', left: 0, right: 0, top: 38, textAlign: 'center' }}>
        <div style={{ color: C.mint, fontSize: 14, letterSpacing: '0.3em', fontWeight: 700, textTransform: 'uppercase' }}>
          {scene.eyebrow}
        </div>
        <div style={{ marginTop: 8, font: '600 44px/1.08 Space Grotesk, sans-serif', letterSpacing: '-0.04em' }}>
          {scene.title}
        </div>
        <div style={{ marginTop: 8, color: C.muted, fontSize: 18 }}>{scene.sub}</div>
      </div>
      <div style={{
        position: 'absolute', left: 92, right: 92, top: '50%', height: gridH,
        translate: '0 -42%', display: 'grid',
        gridTemplateColumns: `repeat(5, 1fr)`, gap: 24, alignContent: 'start',
      }}>
        {scene.tiles.map((t, i) => {
          const d = easeIO(Math.max(0, Math.min(1, (p * 1.35 - i * 0.02))));
          const scale = 1.06 - 0.06 * easeIO(Math.max(0, Math.min(1, d * 4)));
          return (
            <div key={t.name} style={{
              display: 'flex', flexDirection: 'column', borderRadius: 10, overflow: 'hidden',
              background: '#0b1210', boxShadow: '0 20px 54px rgba(0,0,0,0.5)',
              opacity: easeIO(Math.max(0, Math.min(1, d * 2.4))), scale: scale.toFixed(4),
            }}>
              <Img src={asset(t.img)} style={{ width: '100%', objectFit: 'cover', aspectRatio: '16 / 9' }} />
              <div style={{
                padding: '7px 8px', background: '#0e1613', borderTop: '1px solid rgba(50,78,64,0.4)',
                color: '#a9bcb1', font: '700 12px DM Sans, sans-serif', letterSpacing: '0.12em',
                textTransform: 'uppercase', textAlign: 'center',
              }}>
                {t.name}
              </div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

// ────────────────────────────────────────────────────────────────
// End scene — Reform final card → "Made with Remotion" credit
// ────────────────────────────────────────────────────────────────
const EndScene: React.FC<{ scene: Extract<Scene, { type: 'end' }> }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const sec = frame / FPS;
  const creditAt = scene.creditAt;
  const cardIn = easeIO(Math.max(0, Math.min(1, (sec - scene.start) / 0.9)));
  const endOp = sec < creditAt ? cardIn : 1 - easeIO(Math.max(0, Math.min(1, (sec - creditAt) / 0.55)));
  const creditIn = sec < creditAt ? 0 : easeIO(Math.max(0, Math.min(1, (sec - creditAt) / 1.0)));
  const creditScale = 0.95 + 0.05 * creditIn;
  return (
    <AbsoluteFill style={{ zIndex: 10 }}>
      <Backdrop />
      {/* Reform final card */}
      <AbsoluteFill style={{ opacity: endOp, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center' }}>
        <RealMark size={132} glow={1.6} />
        <div style={{ marginTop: 26, font: '700 100px/1 Space Grotesk, sans-serif', letterSpacing: '-0.06em' }}>Reform</div>
        <div style={{ marginTop: 20, font: '500 30px Space Grotesk, sans-serif', color: '#e0e6de' }}>
          Build the experience. <span style={{ color: C.amber }}>Understand the signal.</span><br />
          Move faster with one intelligent workflow.
        </div>
        <div style={{
          marginTop: 36, color: '#e0e6de', font: '500 20px monospace',
          padding: '12px 26px', border: `1px solid ${C.line}`, borderRadius: 999, background: 'rgba(15,22,20,0.7)',
        }}>
          reform-7jo8.onrender.com
        </div>
        <div style={{ display: 'flex', gap: 14, marginTop: 30 }}>
          {['AI-native', 'Built on Xano', 'Built for teams'].map((t) => (
            <span key={t} style={{
              color: C.mint, border: '1px solid rgba(110,224,164,0.35)', background: 'rgba(110,224,164,0.05)',
              padding: '10px 18px', borderRadius: 999, fontSize: 15, fontWeight: 600,
            }}>{t}</span>
          ))}
        </div>
        <div style={{ marginTop: 40, color: C.muted2, fontSize: 13, letterSpacing: '0.24em', textTransform: 'uppercase', fontWeight: 600 }}>
          Xano Hackathon 2026 · Reform
        </div>
      </AbsoluteFill>
      {/* Remotion credit */}
      <AbsoluteFill style={{
        opacity: creditIn, background: 'linear-gradient(160deg, #050708, #0b0e10 55%, #050708)',
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center',
      }}>
        <Img src={asset('remotion-lockup-dark.png')} style={{
          width: 540, objectFit: 'contain', marginBottom: 26, filter: 'drop-shadow(0 16px 70px rgba(0,0,0,0.7))',
          scale: creditScale.toFixed(4),
        }} />
        <div style={{ font: '600 44px Space Grotesk, sans-serif', letterSpacing: '-0.02em' }}>
          This video was made with Remotion
        </div>
        <div style={{ marginTop: 16, color: C.muted, fontSize: 21 }}>
          Every frame — written in React, rendered programmatically.
        </div>
        <div style={{
          marginTop: 28, color: '#c3cfc8', font: '500 19px monospace', letterSpacing: '0.08em',
          border: '1px solid rgba(130,150,140,0.3)', padding: '10px 22px', borderRadius: 999, background: 'rgba(255,255,255,0.03)',
        }}>
          remotion.dev
        </div>
        <div style={{ marginTop: 16, fontSize: 13, letterSpacing: '0.26em', color: '#6b8178', textTransform: 'uppercase', fontWeight: 600 }}>
          Reform · Xano Hackathon 2026
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

// ────────────────────────────────────────────────────────────────
// Composition
// ────────────────────────────────────────────────────────────────
const SceneRenderer: React.FC<{ scene: Scene }> = ({ scene }) => {
  switch (scene.type) {
    case 'title': return <TitleScene scene={scene} />;
    case 'media': return <MediaScene scene={scene} />;
    case 'grid': return <GridScene scene={scene} />;
    case 'end': return <EndScene scene={scene} />;
    default: return null;
  }
};

export const ReformHackathon: React.FC = () => {
  const frame = useCurrentFrame();
  const sec = frame / FPS;
  const scene = currentScene(sec);
  const index = SCENES.findIndex((s) => s === scene);
  return (
    <AbsoluteFill style={{ width: W, height: H, background: C.bg, color: C.text, fontFamily: 'DM Sans, Arial, sans-serif' }}>
      <Audio src={asset('voice-3min.wav')} volume={1} />
      <Audio src={asset('music.mp3')} volume={0.065} loop />
      <SceneRenderer scene={scene} />
      <Rail scene={scene} index={index} />
      <Vignette />
    </AbsoluteFill>
  );
};

export const REFORM_HACKATHON_DURATION = DURATION;
